### ISSUE TITLE
Error during mirah precompilation

### ISSUE THREAD

**Issue by JrmyDev** [shannah/cn1-mirah-json-macros#6]
It stuck on this line in an interface, probably at this statement : 

`<T extends BaseObject> T saveObject(T bo) throws Exception ;`

I've this stack : 

> `C:\Users\jmarquer\Documents\NetBeansProjects\CliniPAD\nbproject\mirah-build-cn1.xml:152: 
> java.lang.RuntimeException: Could not find class for T
>     at ca.weblite.asm.JavaExtendedStubCompiler$2.visitMethod(JavaExtendedStubCompiler.java:418)
>     at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:794)
>     at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
>     at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
>     at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
>     at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
>     at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
>     at ca.weblite.asm.JavaExtendedStubCompiler$2.visitClass(JavaExtendedStubCompiler.java:768)
>     at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:714)
>     at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
>     at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
>     at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
>     at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:120)
>     at ca.weblite.asm.JavaExtendedStubCompiler$2.visitCompilationUnit(JavaExtendedStubCompiler.java:275)
>     at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:550)
>     at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
>     at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
>     at ca.weblite.asm.JavaExtendedStubCompiler.compile(JavaExtendedStubCompiler.java:797)
>     at ca.weblite.asm.JavaExtendedStubCompiler.compileFile(JavaExtendedStubCompiler.java:174)
>     at ca.weblite.asm.JavaExtendedStubCompiler.compileDirectory(JavaExtendedStubCompiler.java:211)
>     at ca.weblite.asm.JavaExtendedStubCompiler.compileDirectory(JavaExtendedStubCompiler.java:214)
>     at ca.weblite.asm.JavaExtendedStubCompiler.compileDirectory(JavaExtendedStubCompiler.java:214)
>     at ca.weblite.asm.JavaExtendedStubCompiler.compileDirectory(JavaExtendedStubCompiler.java:214)
>     at ca.weblite.asm.JavaExtendedStubCompiler.compileDirectory(JavaExtendedStubCompiler.java:214)
>     at ca.weblite.asm.JavaExtendedStubCompiler.compileDirectory(JavaExtendedStubCompiler.java:193)
>     at ca.weblite.asm.WLMirahCompiler.compile(WLMirahCompiler.java:208)
>     at ca.weblite.mirah.ant.MirahcTask.execute(MirahcTask.java:158)
>     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
>     at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
>     at org.apache.tools.ant.Task.perform(Task.java:348)
>     at org.apache.tools.ant.Target.execute(Target.java:435)
>     at org.apache.tools.ant.Target.performTasks(Target.java:456)
>     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
>     at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
>     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
>     at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
>     at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:286)
>     at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:555)
>     at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:153)`

Thanks, in advance.

**Comment by shannah** [comment]
I seem to recall fixing an issue like this.  Check in your netbeans plugins manager and make sure you are using the latest version of the Netbeans Mirah plugin.

**Comment by JrmyDev** [comment]
Sure, I've done the last update...

**Comment by JrmyDev** [comment]
Any news ?
